#
# Makefile for the linux kernel.
# 
#


ifdef CONFIG_ARCH_CELESTIAL
obj-$(CONFIG_VGA_SWITCHER_SUPPORT) += vga_switcher.o
obj-$(CONFIG_CELESTIAL_I2C)  += cnc18xx_i2c.o
obj-$(CONFIG_CELESTIAL_SCI)  += cnc18xx_sci.o
obj-$(CONFIG_CELESTIAL_GPIO) += cnc18xx_gpio.o
obj-$(CONFIG_CELESTIAL_FPC)  += cnc18xx_fpc.o
obj-$(CONFIG_CELESTIAL_WDT)  += cnc18xx_wdt.o
obj-$(CONFIG_CELESTIAL_WDT)  += cnc18xx_wdt.o
obj-$(CONFIG_CELESTIAL_SEC)  += cnc18xx_sec.o
endif
