#
# Makefile for the Linux kernel device drivers.
#
# 15 Sep 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#

obj-y				+= peripheral/
obj-$(CONFIG_CELESTIAL_DF)	+= df/
obj-$(CONFIG_CELESTIAL_XPORT)	+= xport/
obj-$(CONFIG_CELESTIAL_VIDEO)   += video/
obj-$(CONFIG_CELESTIAL_AUDIO)	+= audio/
obj-$(CONFIG_CELESTIAL_GRAPHICS)+= graphics/
obj-$(CONFIG_CELESTIAL_HDMI)	+= hdmi/
