#
# Makefile for the linux kernel.
# 
#

obj-$(CONFIG_MACH_CELESTIALSEMI_CSM1201) += 
obj-$(CONFIG_MACH_CELESTIALSEMI_CSM1800H) += csm1800_audio.o
obj-$(CONFIG_MACH_CELESTIAL_CNC1800L) += cnc1800_audio.o

