#
# Makefile for the linux kernel

ifdef CONFIG_CELESTIAL_XPORT
obj-$(CONFIG_ARCH_CELESTIAL) +=xport_filter1800.o xport_mips1800.o
obj-$(CONFIG_MACH_CELESTIAL_CNC1800L) +=xport_dma1800.o xport_drv1800.o 
obj-$(CONFIG_MACH_CELESTIAL_CNC1800H) +=xport_dma1800h.o xport_drv1800h.o 
endif
