#ifndef __VIDEO_REG_DEF_H__
#define __VIDEO_REG_DEF_H__

#ifdef __cplusplus
extern "C" {
#endif

#define HOST_IF_VID_CMD             	(0x00)
#define HOST_IF_VID_STA             	(0x01)
#define HOST_IF_VID_ENA       		(0x02)
//#define HOST_IF_VID_COP_INT        	(0x03)
//#define HOST_IF_VID_COP_MASK        	(0x04)
//#define HOST_IF_VID_HOST_INT        	(0x05)
//#define HOST_IF_VID_HOST_MASK       	(0x06)

#define HOST_IF_VID_CPBDIRU0           	(0x07)
#define HOST_IF_VID_CPBDIRL0           	(0x08)
#define HOST_IF_VID_CPBDIRRP0          	(0x09)
#define HOST_IF_VID_CPBDIRWP0		(0x0a)
#define HOST_IF_VID_HISTC      		(0x0b)
#define HOST_IF_VID_STC        		(0x0c)
#define HOST_IF_VID_CPBDIRU1           	(0x0d)
#define HOST_IF_VID_CPBDIRL1           	(0x0e)
#define HOST_IF_VID_CPBDIRRP1          	(0x0f)
#define HOST_IF_VID_CPBDIRWP1          	(0x10)
#define HOST_IF_VID_HISTC1          	(0x11)
#define HOST_IF_VID_STC1            	(0x12)

#define HOST_IF_VID_DPB0            	(0x13)
#define HOST_IF_VID_DPB1            	(0x14)
#define HOST_IF_VID_UDB             	(0x15)

#define HOST_IF_VID_DF0_CMD         	(0x16)
#define HOST_IF_VID_DF0_ADDR        	(0x17)
#define HOST_IF_VID_DF0_STA0        	(0x18)
#define HOST_IF_VID_DF0_STA1        	(0x19)
#define HOST_IF_VID_DF0_STA2        	(0x1a)
#define HOST_IF_VID_DF1_CMD         	(0x1b)
#define HOST_IF_VID_DF1_ADDR        	(0x1c)
#define HOST_IF_VID_DF1_STA0        	(0x1d)
#define HOST_IF_VID_DF1_STA1        	(0x1e)
#define HOST_IF_VID_DF1_STA2        	(0x1f)

/* 16 mailbox */
#define HOST_IF_VID_MIPS_MAILBOX_0  	(0x20)
#define HOST_IF_VID_MIPS_MAILBOX_1 	(0x21)
#define HOST_IF_VID_MIPS_MAILBOX_2  	(0x22)
#define HOST_IF_VID_MIPS_MAILBOX_3  	(0x23)
#define HOST_IF_VID_MIPS_MAILBOX_4  	(0x24)
#define HOST_IF_VID_MIPS_MAILBOX_5  	(0x25)
#define HOST_IF_VID_MIPS_MAILBOX_6  	(0x26)
#define HOST_IF_VID_MIPS_MAILBOX_7  	(0x27)
#define HOST_IF_VID_MIPS_MAILBOX_8  	(0x28)
#define HOST_IF_VID_MIPS_MAILBOX_9  	(0x29)
#define HOST_IF_VID_MIPS_MAILBOX_10 	(0x2a)
#define HOST_IF_VID_MIPS_MAILBOX_11 	(0x2b)
#define HOST_IF_VID_MIPS_MAILBOX_12 	(0x2c)
#define HOST_IF_VID_MIPS_MAILBOX_13 	(0x2d)
#define HOST_IF_VID_MIPS_MAILBOX_14 	(0x2e)
#define HOST_IF_VID_MIPS_MAILBOX_15 	(0x2f)
#define HOST_IF_VID_MIPS_MAILBOX_16     (0x3d)
#define HOST_IF_VID_MIPS_MAILBOX_17   (0x3e)
#define HOST_IF_VID_MIPS_MAILBOX_18   (0x3f)
#define HOST_IF_VID_MIPS_MAILBOX_19   (0x40)
#define HOST_IF_VID_MIPS_MAILBOX_20   (0x41)
#define HOST_IF_VID_MIPS_MAILBOX_21   (0x42)
#define HOST_IF_VID_MIPS_MAILBOX_22   (0x43)
#define HOST_IF_VID_MIPS_MAILBOX_23   (0x44)
#define HOST_IF_VID_MIPS_MAILBOX_24   (0x45)
#define HOST_IF_VID_MIPS_MAILBOX_25   (0x46)
#define HOST_IF_VID_MIPS_MAILBOX_26   (0x47)
#define HOST_IF_VID_MIPS_MAILBOX_27   (0x48)
#define HOST_IF_VID_MIPS_MAILBOX_28   (0x49)
#define HOST_IF_VID_MIPS_MAILBOX_29   (0x4a)
#define HOST_IF_VID_MIPS_MAILBOX_30   (0x4b)
#define HOST_IF_VID_MIPS_MAILBOX_31   (0x4c)
#define HOST_IF_VID_MIPS_MAILBOX_32   (0x4d)

#define HOST_IF_VID_MIPS_STA0       	(0x30)
#define HOST_IF_VID_MIPS_STA1       	(0x31)
#define HOST_IF_VID_MIPS_STA2       	(0x32)
#define HOST_IF_VID_DEBUG           	(0x33)
//#define HOST_IF_VID_EOI             	(0x34)
//#define HOST_IF_VID_CMD_AE          	(0x35)
//#define HOST_IF_VID_INT_STA         	(0x36)
//#define HOST_IF_VID_INT_CLR         	(0x37)
//#define HOST_IF_VID_WRITE_STA       	(0x38)
#define HOST_IF_VID_CPB0_TYPE       	(0x39)
#define HOST_IF_VID_CPB1_TYPE       	(0x3a)
#define HOST_IF_VID_TIMER0          	(0x3b)
#define HOST_IF_VID_TIMER1          	(0x3c)

#define HOST_IF_PLUTO_PPBL0_ADDR    	(0x3d)
#define HOST_IF_PLUTO_PPBU0_ADDR    	(0x3e)
#define HOST_IF_PLUTO_PPBRP0_ADDR  	(0x3f)
#define HOST_IF_PLUTO_PPBWP0_ADDR  	(0x40)
#define HOST_IF_PLUTO_PPBL1_ADDR    	(0x41)
#define HOST_IF_PLUTO_PPBU1_ADDR    	(0x42)
#define HOST_IF_PLUTO_PPBRP1_ADDR   	(0x43)
#define HOST_IF_PLUTO_PPBWP1_ADDR   	(0x44)
#define HOST_IF_PLUTO_IPREDLB_ADDR  	(0x45)
#define HOST_IF_PLUTO_MVLB_ADDR     	(0x46)
#define HOST_IF_PLUTO_LFLB_ADDR     	(0x47)
#define HOST_IF_PLUTO_MVBUF0_ADDR   	(0x48)
#define HOST_IF_PLUTO_MVBUF1_ADDR   	(0x49)
#define HOST_IF_PLUTO_FW_BASE_ADDR0 	(0x4a)
#define HOST_IF_PLUTO_FW_END_ADDR0  	(0x4b)
#define HOST_IF_PLUTO_FW_BASE_ADDR1 	(0x4c)
#define HOST_IF_PLUTO_FW_END_ADDR1  	(0x4d)


#define CSM_VIDEO_INT_BASE	(0x41c10000)
#define CSM_VIDEO_INT_SIZE	(0x1000)
#define HOST_IF_VID_HOST_INT_ENABLE	(0x0)
#define HOST_IF_VID_HOST_INT_FORCE  (0x4)
#define HOST_IF_VID_HOST_INT (0x32)

#define CSM_VIDEO_RESET_BASE	(0x42100000)
#define CSM_VIDEO_RESET_SIZE	(0x1000)
#define HOST_IF_VID_RESET	(0x80)
#ifdef __cplusplus
}
#endif

#endif
