#
# Makefile for the linux kernel.
# 
#

obj-$(CONFIG_MACH_CELESTIALSEMI_CSM1201) += 
obj-$(CONFIG_MACH_CELESTIALSEMI_CSM1800H) +=  scalor_coeff.o csm1800_df_clock.o csm1800_df.o
obj-$(CONFIG_MACH_CELESTIAL_CNC1800L) +=  cnc1800l_df.o

