#
# Makefile for the Cavium Celestial SoC framebuffer device driver
#




ifdef CONFIG_ARCH_CELESTIAL 
obj-y += cncfb.o 
endif

ifdef CONFIG_MACH_CELESTIAL_CNC1800H
obj-y +=cnc1800h_fb_hw.o 
endif


ifdef CONFIG_MACH_CELESTIAL_CNC1800L
obj-y +=cnc1800l_fb_hw.o 
endif
