obj-$(CONFIG_CN100_MAC)		+= cn100.o
cn100-objs			:=   cn100_main.o    \
                                     cn100_hw.o      \
                                     cn100_mem.o     \
                                     cn100_hash.o    \
                                     cn100_int.o     \
                                     cn100_phy.o     \
                                     cn100_time.o
